name: Waka Readme

permissions:
  contents: write  # penting! biar bisa push ke repo

on:
  schedule:
    # runs at every 12AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # penting agar pakai token kita, bukan default
          fetch-depth: 0

      - name: Generate WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_UPDATED_DATE: false
          SHOW_LANGUAGE_PER_REPO: false

      - name: Add Profile View Counter
        run: |
          COUNTER_LINE="![](https://hit.yhype.me/github/profile?account_id=96577465)"
          if ! grep -Fxq "$COUNTER_LINE" README.md; then
            echo -e "\n$COUNTER_LINE" >> README.md
          fi

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git checkout main
          git pull --rebase origin main || true

          if git diff --quiet README.md; then
            echo "No changes to commit."
          else
            git add README.md
            git commit -m "Update WakaTime stats"
            git push origin main --force
          fi
